name: Latest blog post workflow
on:
  schedule:
    # Runs every hour
    - cron: '2 1 * * *'
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update this repos README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: zzhalelov/blog-post-workflow@master
        with:
          max_post_count: "4"
          feed_list: "https://dev.to/feed/zzhalelov"
